const RequestFailerHandling = (err,callBack)=>{
    callBack("متاسفانه مشکلی رخ داده است مجدد تلاش کنید")
}